{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 349,
   "id": "6e885b7e-5a90-45b8-8315-ac31ff6b63d2",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (590577666.py, line 98)",
     "output_type": "error",
     "traceback": [
      "  \u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[349]\u001b[39m\u001b[32m, line 98\u001b[39m\n\u001b[31m    \u001b[39m\u001b[31mexcept Exception as e:\u001b[39m\n    ^\n\u001b[31mSyntaxError\u001b[39m\u001b[31m:\u001b[39m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pickle\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "# Set page configuration\n",
    "st.set_page_config(page_title=\"Tourism Recommender\", layout=\"wide\")\n",
    "\n",
    "# Load all saved artifacts\n",
    "@st.cache_resource\n",
    "def load_artifacts():\n",
    "    pred_cf = np.load('pred_cf_matrix.npy')\n",
    "    pred_content = np.load('pred_content_matrix.npy')\n",
    "    pred_nn = np.load('pred_nn_matrix.npy')\n",
    "    hybrid = np.load('hybrid_matrix.npy')\n",
    "\n",
    "    with open('user_ids.pkl', 'rb') as f:\n",
    "        user_ids = pickle.load(f)\n",
    "    with open('item_ids.pkl', 'rb') as f:\n",
    "        item_ids = pickle.load(f)\n",
    "    with open('idx_to_item.pkl', 'rb') as f:\n",
    "        idx_to_item = pickle.load(f)\n",
    "    with open('user_to_idx.pkl', 'rb') as f:\n",
    "        user_to_idx = pickle.load(f)\n",
    "    with open('train_seen.pkl', 'rb') as f:\n",
    "        train_seen = pickle.load(f)\n",
    "\n",
    "    attr_meta = pd.read_csv('attraction_metadata.csv')\n",
    "    return pred_cf, pred_content, pred_nn, hybrid, user_ids, item_ids, idx_to_item, user_to_idx, train_seen, attr_meta\n",
    "\n",
    "# Load data\n",
    "pred_cf, pred_content, pred_nn, hybrid, user_ids, item_ids, idx_to_item, user_to_idx, train_seen, attr_meta = load_artifacts()\n",
    "\n",
    "# Recommendation function\n",
    "def recommend_for_user(user_id, score_matrix, top_n=5):\n",
    "    if user_id not in user_to_idx:\n",
    "        return None, None\n",
    "    user_idx = user_to_idx[user_id]\n",
    "    scores = score_matrix[user_idx].copy()\n",
    "    seen = train_seen.get(user_idx, set())\n",
    "    # Mask seen items\n",
    "    for i in seen:\n",
    "        scores[i] = -np.inf\n",
    "    # Get top indices\n",
    "    top_indices = np.argsort(scores)[::-1][:top_n]\n",
    "    top_scores = scores[top_indices]\n",
    "    # Convert indices to attraction names and scores\n",
    "    recommendations = [(idx_to_item[i], scores[i]) for i in top_indices]\n",
    "    return recommendations, seen\n",
    "\n",
    "# Streamlit UI\n",
    "st.title(\"🎯 Personalized Tourism Recommender\")\n",
    "st.markdown(\"Enter a tourist ID to get top attraction recommendations based on their past ratings.\")\n",
    "\n",
    "# Input\n",
    "tourist_id = st.text_input(\"Tourist ID\", value=\"605\")\n",
    "if tourist_id:\n",
    "    try:\n",
    "        tourist_id_int = int(tourist_id)\n",
    "    except ValueError:\n",
    "        st.error(\"Please enter a valid integer Tourist ID.\")\n",
    "        st.stop()\n",
    "\n",
    "    # Check if tourist exists\n",
    "    if tourist_id_int not in user_to_idx:\n",
    "        st.warning(f\"Tourist ID {tourist_id_int} not found in the system. Showing popular attractions instead.\")\n",
    "        # Fallback: show global popularity (you could pre‑compute popularity scores)\n",
    "        # For simplicity, we can show default recommendations using hybrid matrix for a random user\n",
    "        # Here we just show a message.\n",
    "        st.info(\"Displaying a sample of popular attractions (not personalised).\")\n",
    "        # You could load a popularity vector if you saved it.\n",
    "        # For now, we'll stop.\n",
    "        st.stop()\n",
    "    else:\n",
    "        # Get recommendations using the hybrid model (you can let the user choose)\n",
    "        recommendations, seen = recommend_for_user(tourist_id_int, hybrid, top_n=5)\n",
    "\n",
    "        # Display past ratings\n",
    "        st.subheader(\"📋 Your Previous Ratings\")\n",
    "        # We need to fetch past ratings from training data; if not saved, we can't.\n",
    "        # You can save the train_df as well, or compute from train_seen and a ratings matrix.\n",
    "        # For brevity, we show a placeholder.\n",
    "        st.info(\"Past ratings are shown in the notebook; for the app, you can load a CSV with user ratings.\")\n",
    "        # Alternatively, we can load a pre‑saved user_ratings.csv.\n",
    "\n",
    "        # Display recommendations\n",
    "        st.subheader(\"🌟 Top 5 Recommended Attractions\")\n",
    "        cols = st.columns(5)\n",
    "        for i, (name, score) in enumerate(recommendations):\n",
    "            with cols[i]:\n",
    "                st.markdown(f\"**{name}**\")\n",
    "                st.caption(f\"Score: {score:.3f}\")\n",
    "                # You can also display category, level, etc. from attr_meta\n",
    "                meta = attr_meta[attr_meta['attraction_name'] == name].iloc[0]\n",
    "                st.caption(f\"Category: {meta['attraction_category']}\")\n",
    "                st.caption(f\"Level: {meta['attraction_level']}\")\n",
    "\n",
    "except Exception as e:\n",
    "    st.error(f\"An error occurred: {e}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e4f05c1d-9645-4345-b28e-bd48588012f6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
